---
- name: get device standards for gold template
  hosts: all

  tasks:
#    - name: I hate you. Is it not a core module?
#        junos_get_config:
#        host: "{{ ansible_host }}"
#        username: hpbob
#        password: radius

    - junos_get_facts:
        host: "{{ inventory_hostname }}"
        username: "hpbob"
        password: "radius"

    - debug:
        msg:
