---
- name: IOS Example. Why deleted?
  hosts: cisco.ourzoo.us
  vars: 
    creds: 
      host: "{{ ansible_host }}"
      username: hpbob
      password: radius

  tasks:
    - ios_facts:
        provider: "{{ creds }}"
      tags: facts_only

    - debug:
        msg: "{{ hostvars[inventory_hostname] }}" 
