# https://www.juniper.net/documentation/en_US/junos-ansible/topics/reference/general/junos-ansible-modules-overview.html
# Some of 
# sudo yum install gcc
# sudo yum install nc
# sudo yum install python2-distutils-extra
# sudo yum install libxml2
# sudo yum install libxml2-devel
# sudo yum install python-devel
# sudo yum install libxml2-devel
# sudo yum install libxml2-python
# sudo yum install python-lxml
# sudo yum install libxslt-devel
# sudo pip install pip==9.0.3
# sudo pip install setuptools --upgrade
# sudo pip install PyYAML --upgrade
# sudo pip install junos-eznc
# sudo pip install jxmlease
# and
# ansible-galaxy install Juniper.junos
---
- name: Get Device Facts
  hosts: 192.168.1.88
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Configure test. uncommitted changes will be discarded on exit.
    juniper_junos_config:
      load: set
      config_mode: private
      commit: false
      template: templates/juniper_vpc_primary.j2
      diffs_file: diff_primary.txt
      vars:
        ritm: RITM0021502
        subnet: 10.121.0.64/26
        primary_interface: ge-2/0/0
        vlan_id: 2935
        primary_vif_id: dxvif-fgnyol3v
        address_as1248_primary: 
        address_amazon_primary: 
        primary_auth: 0xLnnar6jSCW3XdF8o0TLVM9
       
      

        
#---
#- name: Get Device Facts
#  hosts: 192.168.1.88
#  roles:
#    - Juniper.junos
#  connection: local
#  gather_facts: no
#
#  vars:
#    ansible_python_interpreter: "/usr/local/bin/python"
#
#  tasks:
#    - name: Retrieve facts from device running Junos OS
#      juniper_junos_facts:
#        host: "{{ inventory_hostname }}"
#        savedir: "{{ playbook_dir }}"
#
#    - name: Print version
#      debug:
#        var: junos.version
