---
- name: 
  hosts: jsw-mgmt.ourzoo.us

  tasks: 
    - napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "hpbob"
        password: "radius"
        dev_os: "junos"
      register: facts
