---
- name: NAPALM PING
  hosts: 192.168.1.88
  connection: local

  tasks: 
  - napalm_ping:
      hostname: "{{ inventory_hostname }}"
      username: root
      password: MJU&6tfc
      dev_os: "junos"
      destination: 8.8.8.8
      count: 2
