---
- name: Implement RFC-72868 for RITM0021381
  hosts: 192.168.1.88
  gather_facts: true
  connection: local

  tasks:
  - name: set vlan
    set_fact:
      vlan_id: "2135"

  - name: set ritm
    set_fact:
      ritm: RITM0021381

  - name: set subnet
    set_fact:
      subnet: 1.2.3.4/28

  - name: set VIF ID
    set_fact:
      vif_id: >-
        {% if   inventory_hostname == '192.168.1.88' %}dxvif-fg4n9lew
        {% elif inventory_hostname == 'us-ash-colo-inet02' %}dxvif-ffqrqzwu
        {% endif %}
    failed_when: vif_id is not defined

  - name: set as1248 address
    set_fact:
      address_as1248: >-
        {% if   inventory_hostname == '192.168.1.88' %}169.254.249.114/30
        {% elif inventory_hostname == 'us-ash-colo-inet02' %}169.254.249.118/30
        {% endif %}
    failed_when: address_as1248 is not defined

  - name: set amazon address
    set_fact:
      address_amazon: >-
        {% if   inventory_hostname == '192.168.1.88' %}169.254.249.113/30
        {% elif inventory_hostname == 'us-ash-colo-inet02' %}169.254.249.117/30
        {% endif %}
    failed_when: address_amazon is not defined

  - name: set auth
    set_fact:
      auth: >-
        {% if   inventory_hostname == '192.168.1.88' %}0xTFGZmIbH5zVJI0i8OGqCG_
        {% elif inventory_hostname == 'us-ash-colo-inet02' %}0xLstBHYQtHKLkvdk2.8DIqD
        {% endif %}
    failed_when: auth is not defined

  - name: set interface
    set_fact:
      interface: >-
        {% if   inventory_hostname == '192.168.1.88' %}fe-0/0/0{% elif inventory_hostname == 'us-ash-colo-inet02' %}fe-0/0/0{% endif %}
    failed_when: interface is not defined

  - name: Create changes from template.
    template:
      src: ./template.j2
      dest: ./RITM0021381-{{ inventory_hostname }}.txt

#  - napalm_install_config:
#      hostname: 192.168.1.88
#      dev_os: "junos"
#      username: root
#      password: MJU&6tfc
#      config_file: "./RITM0021381-{{ ansible_host }}.txt"
#      commit_changes: True
#      #replace_config: True
#      diff_file: "./RITM0021381-{{ inventory_hostname }}.diff"




