---

- name: upgrade yum packages on servers.
  hosts: all

  tasks:
  - name: Upgrade all packages
    yum: name=* state=latest
    become: true

  - name: Install Epel and yum-utils
    yum: name=epel-release,yum-utils 
    become: true

  - name: Install Ansible
    yum: name=ansible
    become: true

  - name: Install Git
    yum: name=git
    become: true

  # add warren to wheel group
  # amend /etc/sudoers

  - name: update pip so python doesn't whine
    pip: name=pip state=latest
    become: true

  - name: Install psycopg2 with pip
    pip: name=psycopg2
    become: true
