---
- name: Initial user account. Normally this would be done by kickstart post-install, but raspberry-pi is not kickstarted.
  user:
    name: warren
    comment: Warren Matthews
    group: wheel
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: ansible_architecture == "armv7l"

- name: Set authorized key taken from file
  authorized_key:
    user: warren
    state: present
    key: "{{ lookup('file', '/home/warren/.ssh/id_rsa.pub') }}"


#  hosts: all
#  get_facts: true
#
#  tasks:
#  - name: set hostname
#
#
#  - name: set static IP 192.168.1.28
#
#  # install git
#
#  # NOT ON BOBBYK yum install docker

  #- name: adduser. Normally this would be done by kickstart post-install, but raspberry-pi is not kickstarted.
  #  user:
  #    name: warren
  #    comment: Warren Matthews
  #    group: wheel
  #    shell: /bin/bash
  #  when: architecture is armv7l


#  debug:
#    msg: "{{ ansible_facts }}" 

# ssh keygen

# copy keys

# sshd no root login

# maybe key only

## vimrc
#
## bash profile x ls history
#
## Pause to add key to github 
## clone ansible
#
#  - name: Install dnsmasq
#    yum:
#      name: dnsmasq,dnsmasq-utils
#    become: true
#
##dhcpd
##tftpd
##pxe
#
##nfs





